variables:
  IMAGE_NAME: vund1993/learn-cicd
  IMAGE_TAG: python-app

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $docker_user -p $docker_pass
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker image push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $was_ssh_key
  script:
    ssh -o StrictHostKeyChecking=no -i $was_ssh_key  ubuntu@13.229.110.215 "
      docker login -u $docker_user -p $docker_pass &&
      docker ps -aq | xargs -r docker stop | xargs -r docker rm &&
      docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"

